/product/{id}:
  methods: [ GET, POST ]
  responses:
    200:
      format: string
      content: '200'
    404:
      format: json
      content: '404'
/product/{id}/settings:
  methods: [ GET, POST ]
  responses:
    200:
      format: string
      content: '200'
    404:
      format: json
      content: '402'