/user/{id}:
  methods: [ GET, POST ]
  responses:
    200:
      format: string
      content: '{
        "id":"5e8e44a0-2552-4acc-9964-f5ca07948486",
        "payload":{
          "name":"Ken",
          "email":"ken@elmo.com"
        },
        "created_at":"2022-09-05 03:37:54"
      }'
    404:
      format: json
      content: '{
        "error":"User Not Found"
      }'
/user/{id}/settings:
  methods: [ GET, POST ]
  responses:
    200:
      format: string
      content: '200'
    404:
      format: json
      content: '404'